global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ml_model_api'
    static_configs:
      - targets: ['ml_api:8001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
